services:
  jupyter:
    image: custom-jupyter:local
    build:
      context: ./jupyter
    volumes:
      - ../data/jupyter:/home/jovyan/work
      - ./jupyter/config:/home/jovyan/.jupyter
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
      SPARK_MASTER: spark://spark-master:7077
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ICEBERG_CATALOG_URI: http://iceberg-rest:8181
    depends_on:
      spark-master:
        condition: service_started
      minio:
        condition: service_healthy
      iceberg-rest:
        condition: service_healthy
    networks:
      - pipeline_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  pipeline_net:
    external: true
