version: "3.8"

services:
  nifi:
    image: custom-nifi:local
    build:
      context: ./nifi
    ports:
      - "8443:8443"
    volumes:
      - ./nifi/config/nifi.properties:/opt/nifi/nifi-current/conf/nifi.properties
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
      SINGLE_USER_CREDENTIALS_USERNAME: ${NIFI_USERNAME}
      SINGLE_USER_CREDENTIALS_PASSWORD: ${NIFI_PASSWORD}
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - pipeline_net
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8443/nifi-api/system-diagnostics"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  pipeline_net:
    external: true
