jobmanager.rpc.address: flink-jobmanager
jobmanager.rpc.port: 6123
jobmanager.memory.process.size: 1600m

taskmanager.memory.process.size: 1728m
taskmanager.numberOfTaskSlots: 2

parallelism.default: 1

blob.server.port: 6124
query.server.port: 6125

rest.port: 8081
