name: Sync Data Folder from ETL to Main

on:
  push:
    branches:
      - etl
    paths:
      - 'data/**'

jobs:
  sync-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Critical for pushing

    steps:
      - name: Checkout ETL branch
        uses: actions/checkout@v4
        with:
          ref: etl
          path: etl

      - name: Checkout Main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
          # token is automatically provided by GITHUB_TOKEN

      - name: Sync data folder
        run: |
          rm -rf main/data
          cp -r etl/data main/data

      - name: Commit & push to main
        run: |
          cd main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add data/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git pull origin main  # Ensure we're up to date
            git commit -m "Sync data folder from etl branch [skip ci]"
            git push origin main
          fi
          