name: Run Malaria Predictions (Every 10 Mins)

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Run on pushes to main branch
  pull_request:
    branches:
      - main

jobs:
  run_predictions:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For checkout, committing, and merging
      actions: write   # For uploading artifacts
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: main  # Checkout the main branch

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy tensorflow==2.19.0 xgboost logging pathlib  numpy datetime sys
       
    - name: Run Prediction Script
      run: python scripts/generate_district_predictions.py

    - name: Commit and Push Results to Main Branch
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add results/*.csv
        git add results/prediction.log
        git commit -m "Add malaria prediction results for run ${{ github.run_id }} on main branch" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: success()

    - name: Merge Results to Dashboard Branch
      run: |
        git fetch origin
        git checkout malaria-cases-dashboard
        git pull origin malaria-cases-dashboard
        git checkout main -- results/
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add results/
        git commit -m "Update prediction results from main for run ${{ github.run_id }}"
        git push origin malaria-cases-dashboard
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: success()

    - name: Upload Prediction Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: malaria-predictions-output-${{ github.run_id }}
        path: results/*.csv
        retention-days: 7
