name: Run National Monthly DDD Predictions

on:
  schedule:
    - cron: '*/10 * * * *'  # Run at midnight on the 1st of each month
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main  # Run on pushes to main branch
  pull_request:
    branches:
      - main

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For checkout, committing, and merging
      actions: write   # For uploading artifacts
    steps:
      - name: Checkout repository (main branch)
        uses: actions/checkout@v4
        with:
          ref: main  # Ensure we checkout the main branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install papermill pandas tensorflow numpy jupyter
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: Run prediction notebook
        run: |
          export TF_CPP_MIN_LOG_LEVEL=2
          mkdir -p results
          papermill docker/notebooks/generate_predictions.ipynb docker/notebooks/output_predictions.ipynb -p output_dir results -p month_str $(date +"%Y_%m")
          
          # Verify output was created
          MONTH_STR=$(date +"%Y_%m")
          if [ ! -f "results/predictions_${MONTH_STR}.csv" ]; then
            echo "::error::Prediction file not generated!"
            exit 1
          fi

      - name: Combine predictions
        run: |
          # Get current month's file
          CURRENT_FILE="results/predictions_$(date +'%Y_%m').csv"
          
          # Check if master file exists
          if [ -f "results/predictions.csv" ]; then
            echo "Appending new predictions to master file"
            # Verify headers match
            if ! diff <(head -1 "$CURRENT_FILE") <(head -1 "results/predictions.csv"); then
              echo "::error::CSV headers don't match!"
              exit 1
            fi
            # Append data (skip header)
            tail -n +2 "$CURRENT_FILE" >> "results/predictions.csv"
          else
            echo "Creating new master predictions file"
            cp "$CURRENT_FILE" "results/predictions.csv"
          fi

      - name: Archive monthly file
        run: |
          mkdir -p results/archive
          mv "results/predictions_$(date +'%Y_%m').csv" "results/archive/"

      - name: Commit and push changes to main branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --ff-only
          git add results/predictions.csv
          git add results/archive/
          git commit -m "Update predictions for $(date +'%Y-%m') on main branch" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success()

      - name: Merge main into anti-malarial-ddd-prediction-dashboard
        run: |
          git fetch origin
          git checkout anti-malarial-ddd-prediction-dashboard
          git merge -X theirs main --no-ff -m "Merge prediction results from main to anti-malarial-ddd-prediction-dashboard for $(date +'%Y-%m')"
          git push origin anti-malarial-ddd-prediction-dashboard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success()

      - name: Upload prediction results
        uses: actions/upload-artifact@v4
        with:
          name: monthly-predictions-output-${{ github.run_id }}
          path: results/*.csv
          retention-days: 7
