name: Run Monthly DDD Predictions

on:
  schedule:
    - cron: '*/10 * * * *'  # Run at midnight on the 1st of each month
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install numpy pandas tensorflow==2.19.0 xgboost logging pathlib  numpy datetime argparse

      - name: Run prediction script
        run: |
          export TF_CPP_MIN_LOG_LEVEL=2
          python scripts/generate_ddd_predictions.py --month-str $(date +"%Y_%m") 2>&1 | tee prediction.log
          if ! ls results/ddd_predictions_*.csv > /dev/null 2>&1; then
            echo "::error::Prediction file not generated!"
            cat prediction.log
            exit 1
          fi

      - name: Commit changes to main branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add results/ddd_predictions_*.csv
          git commit -m "Add predictions for $(date +'%Y-%m')" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success()
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: predictions-${{ github.run_id }}
          path: |
            results/ddd_predictions_*.csv
            prediction.log
          retention-days: 7
        if: always()
        