name: Run Monthly Predictions

on:
  schedule:
    - cron: '*/60 * * * *'  # Every 15 minutes
  workflow_dispatch:      # Allow manual run from GitHub

jobs:
  run-prediction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install papermill tensorflow pandas numpy jupyter
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: Run prediction notebook
        run: |
          export TF_CPP_MIN_LOG_LEVEL=2
          papermill docker/notebooks/generate_predictions.ipynb docker/notebooks/output_predictions.ipynb -p cwd .

      - name: Debug directory contents
        run: |
          ls -R

      - name: Upload predictions
        uses: actions/upload-artifact@v4
        with:
          name: predictions-output
          path: data/predicted_demand_*.csv
